70 dockerize keycloak ssi deployment project
adorsys/keycloak-ssi-deployment pull request #75
Opened 2024-08-08 10:24 UTC by forkimenjeckayang

2024-08-08 14:18 UTC, IngridPuppet commented on 0.start-kc-oid4vci.sh
> -esac
Do we want to drop support for running the start script directly? I don't think so. To retain this support, I suggest to refactor the script by moving the sections that you want to call during docker build to a new script. You may choose to name the new script `build-kc-oid4vci.sh`, and call it both in the start script and in the Dockerfile.

2024-08-08 14:19 UTC, IngridPuppet commented on Dockerfile
> +RUN ./0.start-kc-oid4vci.sh
This runs a start command, while you only want to build at this point. Check my previous comment.

2024-08-08 14:20 UTC, IngridPuppet commented on Dockerfile
> +RUN apt-get update && apt-get install -y git apt-utils
Are you having this twice?

2024-08-08 14:21 UTC, IngridPuppet commented on Dockerfile
> +EXPOSE 8443
Is reusing KEYCLOAK_HTTPS_PORT not appropriate? This may help:
```Dockerfile
# Source the .env file and export variables
RUN set -a && source .env && set +a
```

2024-08-09 11:53 UTC, forkimenjeckayang commented on 0.start-kc-oid4vci.sh
> -esac
Noted Sir 
Will create a new script and use

2024-08-09 11:55 UTC, forkimenjeckayang commented on Dockerfile
> +RUN apt-get update && apt-get install -y git apt-utils
Had issues before when we using just one in the build and runtime phase but will look into again with the new script i will create

2024-08-12 10:14 UTC, IngridPuppet requested changes

2024-08-12 10:14 UTC, IngridPuppet commented on Dockerfile
> +ENTRYPOINT ["sh", "-c", "set -a && . /opt/keycloak/.env && set +a && cd \"$KC_INSTALL_DIR\" && exec bin/kc.sh \"$KC_START\" --features=oid4vc-vci"]
Have you tried running the container with `KC_START` quoted? I have an error that actually makes sense:

```
Option: 'start --hostname-strict' is not expected to contain whitespace, please remove any unnecessary quoting/escaping
Did you mean: kc.sh start or kc.sh start-dev or kc.sh import?
Try 'kc.sh --help' for more information on the available options.
```

```suggestion
ENTRYPOINT ["sh", "-c", "set -a && . /opt/keycloak/.env && set +a && cd \"$KC_INSTALL_DIR\" && exec bin/kc.sh $KC_START --features=oid4vc-vci"]
```

2024-08-12 10:14 UTC, IngridPuppet commented on build-kc-oid4vci.sh
You should reuse this script in `./0.start-kc-oid4vci.sh` to avoid code duplication.

2024-08-12 14:53 UTC, IngridPuppet requested changes
Can you check again ? I can't run the docker image after build.
```
sh: 1: /opt/keycloak/target/tools/keycloak-999.0.0-SNAPSHOT: Permission denied
```

2024-08-12 22:59 UTC, forkimenjeckayang commented
It should work now Sir
Saw what caused the error

2024-08-13 08:33 UTC, IngridPuppet approved these changes

2024-08-13 08:33 UTC, merged